pipeline {

    agent any

    stages {

        stage('Build') {
            steps {
                echo 'Buidling ...'
            }
        }

         stage('Test') {
            steps {
                echo 'Testing ...'
            }
        }

         stage('Deploy') {
            steps {
                echo 'Deploying ...'
            }
        }

    }

}